name: Deploy Lambda Function

on:
  push:
    branches:
      - main 
#asdfg
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Zip Lambda function code
      run: zip -r processCard.zip lambda_function.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code --function-name processCreditCard --zip-file fileb://processCard.zip

