name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Set this to the branch you use for production releases

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure this matches your Lambda runtime

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Lambda
      uses: appleboy/lambda-action@v0.0.2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-west-  # Change this to your Lambda's AWS region
        function_name: my-lambda-function
        zip_file: my-lambda-function.zip
      run: |
        zip -r my-lambda-function.zip .
